export const AUTH_TRY_LOGIN = 'AUTH_TRY_LOGIN';
export const AUTH_TRY_LOGIN_SUCCESS = 'AUTH_TRY_LOGIN_SUCCESS';
export const AUTH_TRY_LOGIN_FAILED = 'AUTH_TRY_LOGIN_FAILED';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';